set pagesize 49999
set trimspool on
set feed off
set head off
set echo off
set verify off
--set termout off

set serveroutput on
DECLARE
v_region_id     NUMBER; 
v_res           NUMBER; 
v_table         varchar(1); 
v_query         varchar(2000);   
v_region_file   varchar(56); 
v_file_mix      varchar(56); 
v_file_gdy      varchar(56); 
v_file_as400    varchar(56); 
v_file_ptx      varchar(56); 
v_zap_table     varchar(56); 
v_dir           varchar(255);   
 CURSOR c_mdl IS
  select  region_id, rtrim(region_constant) as region_constant from	 ZAP_REGION_NAME;
 
BEGIN
v_table := '&1';
IF v_table = 'F' then
   v_zap_table := 'VW_ZAP_FRZ';
ELSIF v_table = 'Z' then
    v_zap_table := 'VW_ZAP';
END IF;  
dbms_output.put_line(v_zap_table);
 
v_dir :='/ads/acct/kevint/Zap/Working'; 
--v_dir :='CDE2_TMP_DIR'; 
  -- = /ads/prod/Cde2/Data/Tmp 
FOR c_mdl_record IN c_mdl 
      LOOP
v_region_id := c_mdl_record.region_id;
v_region_file :=   'zapcdprd.full.' || c_mdl_record.region_constant || '.txt';
v_file_mix :=   v_region_file || '.mix';
v_file_gdy :=   v_region_file || '.gdy';
v_file_as400 :=   v_region_file || '.as400';
v_file_ptx :=   v_region_file || '.ptx';
IF c_mdl_record.region_constant = 'USA' then
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'' , LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and (hidden_flag not in (''A'',''H'',''W'') ) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''),       (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' ''       then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'' , LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( (hidden_flag not in (''A'',''H'')) or (hidden_flag not in (''A'') and national_acct_cd = ''215'') ) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_ptx);
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, (case when  national_acct_cd = ''220'' THEN ''F'' else DECODE(PRIV_PRICE_FLAG,''N'', ''F'', ''Y'', ''Y'', ''F'')  end), ''NOW'' , LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''A'',''H'',''W'',''C'') and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_gdy);
 
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'' , LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( RTRIM(sug_line_txt) is not null or RTRIM(sug_line_txt) != '' '') and mfg_id in (select mfg_id from vw_zap where ( RTRIM(IC_LINE_TXT) is not null or RTRIM(IC_LINE_TXT) != '' '') union select mfg_id from vw_zap where ( RTRIM(cat_line_txt) is not null or RTRIM(cat_line_txt) != '' ''))  and (hidden_flag not in (''A'',''H'',''W'',''C'') ) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_as400);
END IF;
    
IF c_mdl_record.region_constant = 'CANADA' then
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(MFG_NAME),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''),        (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'' , LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and (hidden_flag not in (''A'',''H'',''W'') ) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);

 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'' , LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( (hidden_flag not in (''A'',''H'')) or (hidden_flag  in (''H'') and national_acct_cd = ''220'')) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_ptx);
END IF; 
   
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(MFG_NAME),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''),        (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'' , LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''A'',''H'',''W'',''C'') and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_mix);
 
 
 -- short files
 v_region_file :=   'zapcdprd.short.' || c_mdl_record.region_constant || '.txt';
v_file_mix :=   v_region_file || '.mix';
v_file_gdy :=   v_region_file || '.gdy';
v_file_as400 :=   v_region_file || '.as400';
v_file_ptx :=   v_region_file || '.ptx';
 
 IF c_mdl_record.region_constant = 'USA' then
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and (hidden_flag not in (''A'',''H'',''W'') ) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);
 
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ((hidden_flag not in (''A'',''H'')) or (hidden_flag not in (''A'') and national_acct_cd = ''215'')) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_ptx);

 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, (case when  national_acct_cd = ''220'' THEN ''F'' else DECODE(PRIV_PRICE_FLAG,''N'', ''F'', ''Y'', ''Y'', ''F'')  end), ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''A'',''H'',''W'',''C'') and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_gdy);
 
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( RTRIM(sug_line_txt) is not null or RTRIM(sug_line_txt) != '' '') and mfg_id in (select mfg_id from vw_zap where ( RTRIM(IC_LINE_TXT) is not null or RTRIM(IC_LINE_TXT) != '' '') union select mfg_id from vw_zap where ( RTRIM(cat_line_txt) is not null or RTRIM(cat_line_txt) != '' ''))  and (hidden_flag not in (''A'',''H'',''W'',''C'') ) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_as400);
END IF;
    
IF c_mdl_record.region_constant = 'CANADA' then
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' ''),''T''  , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG,''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and (hidden_flag not in (''A'',''H'',''W'') ) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);

 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' ''),''T''  , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( (hidden_flag not in (''A'',''H'')) or (hidden_flag  in (''H'') and national_acct_cd = ''220'')) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_ptx);
END IF; 
   
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(MFR_NAME),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''),        (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT)        != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,'' ''),1,'' ''),''T''  , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''A'',''H'',''W'',''C'') and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_mix);

 
 
 
 -- non app extracts .na
  -- full files
 v_region_file :=   'zapcdprd.full.' || c_mdl_record.region_constant || '.na';
v_file_mix :=   v_region_file || '.mix';
v_file_gdy :=   v_region_file || '.gdy';
v_file_as400 :=   v_region_file || '.as400';
v_file_ptx :=   v_region_file || '.ptx';
IF c_mdl_record.region_constant = 'USA' then
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and (hidden_flag not in (''H'',''W'') ) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( (hidden_flag not in (''H'')) or (hidden_flag not in (''A'') and national_acct_cd = ''215'')) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_ptx);
 --v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, (case when  national_acct_cd = ''220'' THEN ''F'' else DECODE(PRIV_PRICE_FLAG,''N'', ''F'', ''Y'', ''Y'', ''F'')  end), ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''H'',''W'',''C'') and region_id =' || v_region_id;
 --v_res:=fn_dump_query(v_query,'',v_dir,v_file_gdy);
 
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( RTRIM(sug_line_txt) is not null or RTRIM(sug_line_txt) != '' '') and mfg_id in (select mfg_id from vw_zap where ( RTRIM(IC_LINE_TXT) is not null or RTRIM(IC_LINE_TXT) != '' '') union select mfg_id from vw_zap where ( RTRIM(cat_line_txt) is not null or RTRIM(cat_line_txt) != '' '')) and (hidden_flag not in (''H'',''W'',''C'') ) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_as400);
END IF;
    
IF c_mdl_record.region_constant = 'CANADA' then
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and  hidden_flag != ''H'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);

 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFG_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '''' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' '') ,''T'', DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( (hidden_flag not in (''H'')) or (hidden_flag  in (''H'')  and national_acct_cd = ''220'')) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_ptx);
END IF; 
   
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(MFG_NAME),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''),        (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' ''        then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''H'',''W'',''C'') and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_mix);
 
 
 
  -- na short files
 v_region_file :=   'zapcdprd.short.' || c_mdl_record.region_constant || '.na';
v_file_mix :=   v_region_file || '.mix';
v_file_gdy :=   v_region_file || '.gdy';
v_file_as400 :=   v_region_file || '.as400';
v_file_ptx :=   v_region_file || '.ptx';
  IF c_mdl_record.region_constant = 'USA' then
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and (hidden_flag not in (''H'',''W'') ) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);
 
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ((hidden_flag not in (''H'')) or (hidden_flag not in (''A'') and national_acct_cd = ''215'')) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_ptx);

-- v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, (case when  national_acct_cd = ''220'' THEN ''F'' else DECODE(PRIV_PRICE_FLAG,''N'', ''F'', ''Y'', ''Y'', ''F'')  end), ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''H'',''W'',''C'') and region_id =' || v_region_id;
-- v_res:=fn_dump_query(v_query,'',v_dir,v_file_gdy);
 
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and (hidden_flag not in (''H'',''W'',''C'') ) and ( RTRIM(sug_line_txt) is not null or RTRIM(sug_line_txt) != '' '')  and mfg_id in (select mfg_id from vw_zap where ( RTRIM(IC_LINE_TXT) is not null or RTRIM(IC_LINE_TXT) != '' '') union select mfg_id from vw_zap where ( RTRIM(cat_line_txt) is not null or RTRIM(cat_line_txt) != '' '')) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_as400);

-- special for c2c;
 v_region_file :=   'zapcdprd.stage.' || c_mdl_record.region_constant || '.na';
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and (hidden_flag not in (''H'',''W'') ) and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);
 
END IF;
    
IF c_mdl_record.region_constant = 'CANADA' then
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''H'',''W'',''C'') and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);

 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is  not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and ( (hidden_flag not in (''H'')) or (hidden_flag  in (''H'') and national_acct_cd = ''220'') ) and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_ptx);
-- special for c2c;
 v_region_file :=   'zapcdprd.stage.' || c_mdl_record.region_constant || '.na';
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(upper(MFR_NAME)),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''), (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' '' then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and  hidden_flag != ''H'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_region_file);

END IF; 
   
 v_query := 'select LPAD(order_id,6,'' ''),RPAD(rtrim(MFR_NAME),45,'' ''),   RPAD(NVL(rtrim(LINE_DESC_TXT),'' ''),47,''.''),'' '',(case when  (ltrim(CAT_LINE_TXT) = '''' or ltrim(CAT_LINE_TXT) is null) AND (ltrim(IC_LINE_TXT) != '''' or ltrim(IC_LINE_TXT) is not null) THEN ''-*'' when ltrim(IC_LINE_TXT) = '''' or ltrim(IC_LINE_TXT) is null THEN ''--'' ELSE ''**'' END  ),''   '', RPAD(NVL(SUG_LINE_TXT,''   ''),3,'' ''),      (case when  (ltrim(CAT_LINE_TXT) = '' '' or  ltrim(CAT_LINE_TXT) is null) and ltrim(IC_LINE_TXT) != '' ''         then RPAD(NVL(IC_LINE_TXT,''   ''),3,'' '') else RPAD(NVL(CAT_LINE_TXT,''   ''),3,'' '') end), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(TP_LINE_TXT,''   ''),4,'' ''), RPAD(NVL(GROUP_FLAG,'' ''),1,'' ''), ''___________'',	''       0.0      0       0.0      0       0.0      0'',RPAD(NVL(HIDDEN_FLAG,''   ''),1,'' ''),''T'' , DECODE(PRIV_LINE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_LINE_FLAG, DECODE(PRIV_PRICE_FLAG, ''N'', ''F'', ''Y'', ''Y'', ''F'') PRIV_PRICE_FLAG, ''NOW'', LPAD(nvl(national_acct_cd, '' ''),3,'' '') from	 ' || v_zap_table || ' where status != ''I'' and hidden_flag not in (''H'',''W'',''C'') and full_flag !=''Y'' and region_id =' || v_region_id;
 v_res:=fn_dump_query(v_query,'',v_dir,v_file_mix);

 
 
 END LOOP;

END;

/

exit sql.sqlcode
 
